version: '3'
services:
  clothing-detection: 
    image: 'millenia911/clothing_det:v1-api'
    ports:
      - 8080:8080
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure

  front-end: 
    image: 'millenia911/clothing_det:v1-webhost'
    ports:
      - 5000:5000
    deploy:
      restart_policy:
        condition: on-failure
